title:            $ jekyll serve | Mars, front-end developer.
description:      Powered by a lady developer
baseurl:	  /blog
signoff:          # Mars
disqus_shortname: # 
facebook_appid:   # 
google_analytics: # 

links:
  - name:         about
    url:          /about
  - name:         email
    url:          mailto:marsadie@gmail.com
    external:     true
  - name:         where I work
    url:          http://skreened.com
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
